In [15]:
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score
from sklearn import tree
from sklearn import metrics

for i in range(1,12) :
    testX = np.genfromtxt('gtd_region_test_I_{}.csv'.format(i),delimiter=',')
    testY = np.genfromtxt('gtd_region_test_T_{}.csv'.format(i),delimiter=',')
    trainX = np.genfromtxt('gtd_region_train_I_{}.csv'.format(i),delimiter=',')
    trainY = np.genfromtxt('gtd_region_train_T_{}.csv'.format(i),delimiter=',')
    
    print('\n Region{}'.format(i))
    print('----------')
    
    print('\n Random Forest:')
    clf_rf = RandomForestClassifier(n_estimators=10, max_depth=16)
    scores = cross_val_score(clf_rf, trainX, trainY)
    
    print('CV - {}'.format(scores.mean()))
    
    clf_rf.fit(trainX, trainY)
    predict = clf_rf.predict(testX)
    print('RecallScore - {}'.format(recall_score(testY, predict,average='micro')))
    
    fpr, tpr, thresholds = metrics.roc_curve(testY, predict, pos_label=2)
    print('AUC - {}'.format(metrics.auc(fpr, tpr)))
    
    print('\n Decision Tree:')
    clf = tree.DecisionTreeClassifier(max_depth=8)
    scores = cross_val_score(clf, trainX, trainY)
    
    print('CV - {}'.format(scores.mean()))
    
    clf.fit(trainX, trainY)
    predict = clf.predict(testX)
    print('RecallScore - {}'.format(recall_score(testY, predict,average='micro')))
          
    fpr, tpr, thresholds = metrics.roc_curve(testY, predict, pos_label=2)
    print('AUC - {}'.format(metrics.auc(fpr, tpr)))
    


 Region1
----------

 Random Forest:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.44075924413707074
RecallScore - 0.5097744360902255
AUC - nan

 Decision Tree:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/metrics/ranking.py:542: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)
/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.379178424877711
RecallScore - 0.4330827067669173
AUC - nan


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/metrics/ranking.py:542: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)



 Region2
----------

 Random Forest:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.7567267977167612
RecallScore - 0.7751418256833419
AUC - nan

 Decision Tree:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/metrics/ranking.py:542: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)
/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.8015802163726434
RecallScore - 0.7952552862300155
AUC - nan


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/metrics/ranking.py:542: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)



 Region3
----------

 Random Forest:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.6737094465665701
RecallScore - 0.6995686374016747
AUC - 0.0531860878395532

 Decision Tree:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.6741373615242833
RecallScore - 0.6972849530575996
AUC - 0.0509012439705509

 Region4
----------

 Random Forest:
CV - 0.5756056808688388


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


RecallScore - 0.5060240963855421
AUC - 0.2692307692307693

 Decision Tree:
CV - 0.5883806739069897
RecallScore - 0.4819277108433735
AUC - 0.2846153846153846

 Region5
----------

 Random Forest:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.6222681204647128
RecallScore - 0.6024405908798972
AUC - 0.28245501285347047

 Decision Tree:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.62641358617071
RecallScore - 0.6332691072575466
AUC - 0.1796272493573265

 Region6
----------

 Random Forest:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.6347039458658609
RecallScore - 0.6580133405444384
AUC - nan

 Decision Tree:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/metrics/ranking.py:542: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)
/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.6499729310879699
RecallScore - 0.653145844600685
AUC - nan

 Region7
----------

 Random Forest:
CV - 0.0880952380952381
RecallScore - 0.3333333333333333
AUC - 0.5555555555555556

 Decision Tree:
CV - 0.13809523809523808
RecallScore - 0.2857142857142857
AUC - 0.32407407407407407


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/metrics/ranking.py:542: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)
/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)



 Region8
----------

 Random Forest:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.6204321187185613
RecallScore - 0.6273133375877473
AUC - 0.3774498606606057

 Decision Tree:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.5523503692699295
RecallScore - 0.5456285896617741
AUC - 0.53417241536845

 Region9
----------

 Random Forest:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.6098599278019826
RecallScore - 0.6271929824561403
AUC - 0.9714285714285714

 Decision Tree:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.6080758064817329
RecallScore - 0.6337719298245614
AUC - 0.9428571428571427

 Region10
----------

 Random Forest:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.5931891367490576
RecallScore - 0.6079081069140712
AUC - 0.4388323750552852

 Decision Tree:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.5625080823600997
RecallScore - 0.5663795007731389
AUC - 0.4855594869526758

 Region11
----------

 Random Forest:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.7275820092691467
RecallScore - 0.7676229508196721
AUC - 0.5796744631377376

 Decision Tree:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.6635704947970386
RecallScore - 0.6872950819672131
AUC - 0.3143892764327725


In [17]:
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score
from sklearn import tree
from sklearn import metrics

i = 1
testX = np.genfromtxt('gtd_region_test_I_{}.csv'.format(i),delimiter=',')
testY = np.genfromtxt('gtd_region_test_T_{}.csv'.format(i),delimiter=',')
trainX = np.genfromtxt('gtd_region_train_I_{}.csv'.format(i),delimiter=',')
trainY = np.genfromtxt('gtd_region_train_T_{}.csv'.format(i),delimiter=',')

print('\n Region{}'.format(i))
print('----------')

print('\n Random Forest:')
clf_rf = RandomForestClassifier(n_estimators=10, max_depth=16)
scores = cross_val_score(clf_rf, trainX, trainY)

print('CV - {}'.format(scores.mean()))

clf_rf.fit(trainX, trainY)
predict = clf_rf.predict(testX)
print('RecallScore - {}'.format(recall_score(testY, predict,average='micro')))

fpr, tpr, thresholds = metrics.roc_curve(testY, predict, pos_label=2)
print('AUC - {}'.format(metrics.auc(fpr, tpr)))

print('\n Decision Tree:')
clf = tree.DecisionTreeClassifier(max_depth=8)
scores = cross_val_score(clf, trainX, trainY)

print('CV - {}'.format(scores.mean()))

clf.fit(trainX, trainY)
predict = clf.predict(testX)
print('RecallScore - {}'.format(recall_score(testY, predict,average='micro')))

fpr, tpr, thresholds = metrics.roc_curve(testY, predict, pos_label=2)
print('AUC - {}'.format(metrics.auc(fpr, tpr)))



 Region1
----------

 Random Forest:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.44051818104640844
RecallScore - 0.5157894736842106
AUC - nan

 Decision Tree:


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/metrics/ranking.py:542: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)
/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


CV - 0.37963985028303626
RecallScore - 0.43909774436090226
AUC - nan


/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/metrics/ranking.py:542: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)


In [18]:
fpr

array([ 0.        ,  0.00902256,  0.01804511,  0.01954887,  0.02556391,
        0.02706767,  0.03909774,  0.04360902,  0.11428571,  0.12180451,
        0.17744361,  0.18646617,  0.19398496,  0.20601504,  0.21654135,
        0.22556391,  0.22706767,  0.23458647,  0.33834586,  0.35488722,
        0.37894737,  0.38796992,  0.66917293,  0.7112782 ,  0.71278195,
        0.71578947,  0.72030075,  0.72631579,  0.78496241,  0.83609023,
        0.8406015 ,  0.84360902,  0.85112782,  0.92781955,  0.96390977,
        0.97894737,  1.        ])

In [19]:
tpr

array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan])

In [20]:
predict

array([  92.,   14.,   24.,   40.,   40.,    7.,   40.,   25.,   47.,
         68.,   47.,   40.,    7.,   24.,   40.,    9.,   99.,   24.,
         40.,   86.,   40.,    7.,   64.,    0.,   24.,   37.,    9.,
         92.,   97.,   47.,   24.,   24.,   40.,   86.,    6.,    9.,
         54.,   92.,   24.,    9.,   40.,   68.,   22.,   92.,   22.,
         40.,   40.,   40.,    0.,   58.,   92.,   70.,   47.,   40.,
         58.,   40.,    6.,   40.,   18.,   92.,    9.,   37.,  109.,
         24.,   22.,   99.,    9.,   86.,   40.,   22.,    0.,   40.,
          9.,   45.,    6.,   40.,   24.,   91.,    9.,   58.,   40.,
         79.,   40.,   58.,   99.,   40.,   40.,   54.,  109.,   22.,
         40.,   14.,   58.,   40.,   40.,   58.,   99.,   24.,    6.,
         54.,   54.,   40.,  108.,   24.,   37.,   37.,   40.,    6.,
         68.,   99.,   54.,   40.,  101.,   58.,   40.,   40.,   47.,
         37.,   99.,   45.,   40.,   40.,   54.,    9.,    9.,   37.,
         22.,   40.,

In [21]:
testY

array([  24.,   24.,   58.,   60.,   60.,   37.,   54.,   24.,   36.,
         68.,   36.,   40.,    8.,   27.,   41.,    9.,   99.,   24.,
         40.,    0.,   99.,   18.,   18.,   17.,   28.,   99.,    9.,
         92.,   11.,   95.,   25.,   81.,    5.,   57.,   99.,   37.,
         58.,   92.,   28.,    9.,   40.,   68.,  104.,   92.,   40.,
         60.,   40.,   40.,    0.,   58.,   92.,   70.,   36.,   39.,
         92.,   40.,   37.,   81.,   18.,   58.,    9.,   99.,  109.,
         13.,   70.,   99.,    9.,   26.,   57.,   54.,    0.,   40.,
          9.,   45.,   43.,   57.,   58.,   14.,    9.,   58.,   68.,
         79.,   84.,   82.,   99.,   40.,   54.,   68.,   22.,   34.,
         70.,   14.,   58.,   40.,   70.,   58.,   99.,   24.,    9.,
         54.,   58.,   81.,  108.,   13.,   37.,   37.,   40.,   99.,
         68.,   79.,    4.,   66.,  101.,   82.,   60.,   34.,   47.,
         99.,   57.,   68.,   68.,   68.,   58.,    9.,    9.,   99.,
         68.,   70.,

In [22]:
metrics.roc_curve(testY, predict, pos_label=2)

/Users/bhargavisri/anaconda/lib/python3.5/site-packages/sklearn/metrics/ranking.py:542: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)


(array([ 0.        ,  0.00902256,  0.01804511,  0.01954887,  0.02556391,
         0.02706767,  0.03909774,  0.04360902,  0.11428571,  0.12180451,
         0.17744361,  0.18646617,  0.19398496,  0.20601504,  0.21654135,
         0.22556391,  0.22706767,  0.23458647,  0.33834586,  0.35488722,
         0.37894737,  0.38796992,  0.66917293,  0.7112782 ,  0.71278195,
         0.71578947,  0.72030075,  0.72631579,  0.78496241,  0.83609023,
         0.8406015 ,  0.84360902,  0.85112782,  0.92781955,  0.96390977,
         0.97894737,  1.        ]),
 array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
         nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
         nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
         nan,  nan,  nan,  nan]),
 array([ 110.,  109.,  108.,  107.,  106.,  104.,  101.,  100.,   99.,
          97.,   92.,   91.,   86.,   73.,   70.,   68.,   67.,   64.,
          58.,   54.,   47.,   45.,   40.,   37.,   36.